language: node_js
node_js: 
  - "10"

services:
  - mongodb

install:
  - npm install

env:
  global:
    - NODE_ENV=test

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sleep 15

script:
  - npm test

after_success:
  - ./cc-test-reporter after-build
